micronaut:
  application:
    name: pixKeymanager

datasources:
  default:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update

external-service:
  bcb:
    base-uri: ${EXTERNAL_SERVICE_BCB_BASE_URI}
    pix-create-urn: ${EXTERNAL_SERVICE_BCB_PIX_CREATE_URN}
    pix-delete-urn: ${EXTERNAL_SERVICE_BCB_PIX_DELETE_URN}
  erp-itau:
    base-uri: ${EXTERNAL_SERVICE_ERP_ITAU_BASE_URI}
    consulta-conta-urn: ${EXTERNAL_SERVICE_ERP_ITAU_CONSULTA_CONTA_URN}